/* ASUS RT-N14U */

#define BOARD_PID		"RT-N14U"
#define BOARD_NAME		"RT-N14U"
#define BOARD_DESC		"ASUS RT-N14U Wireless Router"
#define BOARD_VENDOR_NAME	"ASUSTek Computer Inc."
#define BOARD_VENDOR_URL	"http://www.asus.com/"
#define BOARD_MODEL_URL		"http://www.asus.com/Networking/RTN14U/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_RESET
#define BOARD_GPIO_BTN_WPS	1
#undef  BOARD_GPIO_BTN_WLTOG
#undef  BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_WIFI	72
#undef BOARD_GPIO_LED_SW2G
#undef BOARD_GPIO_LED_SW5G
#define BOARD_GPIO_LED_POWER	38
#define BOARD_GPIO_LED_LAN	41
#define BOARD_GPIO_LED_WAN	40
#define BOARD_GPIO_LED_USB	39
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
